[package]
name = "mm2r-toolbox"
version = "1.0.0"
description = "METAL MAX Database 离线工具箱"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
sha2 = "0.10"
zip = "0.6"
tiny_http = "0.12"
urlencoding = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1
